### ISSUE TITLE
does not update when song changes

### ISSUE THREAD

**Issue by roiz-git** [giedriusStan/argos-mpris#1]
only by click

**Comment by Medik-GH** [comment]
Working fine for me on Ubuntu 18.04 with Spotify from Snap repo

**Comment by brandoningli** [comment]
If you look at the Argos documentation, you'll see how renaming the shell script will affect its update cycle. The `1s` before `.sh` means it'll update every 1 second. If it isn't, and you've named the script correctly, it's an Argos issue, and you'd want to file an issue there.

**Comment by roiz-git** [comment]
yep I already did, but time intervals is not a good way to do things, better with event driven approach

**Comment by brandoningli** [comment]
I think not using an event driven approach is a limitation of both the interface with Spotify and Argos itself.

**Comment by roiz-git** [comment]
oh, I use it for MPD

**Comment by AndreiTS** [comment]
I'm also having this issue. The song don't change

![Captura de tela de 2020-04-24 11-09-48](https://user-images.githubusercontent.com/13489837/80221918-603c6b00-861c-11ea-83b1-ef3b8eaa042a.png)

**Comment by roiz-git** [comment]
I lost interest in this, should I leave the issue open?
