### ISSUE TITLE
Hide mpris.1.1s.sh text when no media is playing?

### ISSUE THREAD

**Issue by nickjcoco** [giedriusStan/argos-mpris#4]
Is there a way to hide the mpris text in the top bar while no music is playing?

Would this be done in the mpris file or argos?

Not a dealbreaker, but would be nice for aesthetics. Also not sure if maybe my other extensions or something could be causing it to show while it's inactive.

I'm on Ubuntu 18.04, shell version 3.28.4.

**Comment by giedriusStan** [comment]
hey, do you mean text in top bar is still showing even though spotify is not running at all? Or spotify is still running, but the track is paused?

If spotify is not running, then text is not suppose to be there, however if only track is paused, then it will still show the text.

If you need to change this script behavior in any way then you would only need to edit mpris.1.1s.sh file

**Comment by nickjcoco** [comment]
Yea I'm not sure why, but with Spotify not open it just shows mpris.1.1s.sh in the top bar. This is the only argos extension I have installed at the moment. I wouldn't know what to change in the script, though. Would any other info be helpful? Other tweaks I have or anything?

**Comment by giedriusStan** [comment]
try to execute this command with and without spotify running (this is a command from the script)
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata`

without spotify running it should print "Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files"

**Comment by nickjcoco** [comment]
Without it running you were right, it did return the error.

While running I got:

```
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata

method return time=1568825117.084462 sender=:1.273 -> destination=:1.286 serial=70 reply_serial=2
   variant       array [
         dict entry(
            string "mpris:trackid"
            variant                string "spotify:track:2f9K9Gm9CLj0eKFW3BQZE8"
         )
         dict entry(
            string "mpris:length"
            variant                uint64 301840000
         )
         dict entry(
            string "mpris:artUrl"
            variant                string "https://open.spotify.com/image/fae144690c472216fd467a5291f4c246d612504b"
         )
         dict entry(
            string "xesam:album"
            variant                string "Blood Lust"
         )
         dict entry(
            string "xesam:albumArtist"
            variant                array [
                  string "Uncle Acid & The Deadbeats"
               ]
         )
         dict entry(
            string "xesam:artist"
            variant                array [
                  string "Uncle Acid & The Deadbeats"
               ]
         )
         dict entry(
            string "xesam:autoRating"
            variant                double 0.43
         )
         dict entry(
            string "xesam:discNumber"
            variant                int32 1
         )
         dict entry(
            string "xesam:title"
            variant                string "I'll Cut You Down"
         )
         dict entry(
            string "xesam:trackNumber"
            variant                int32 1
         )
         dict entry(
            string "xesam:url"
            variant                string "https://open.spotify.com/track/2f9K9Gm9CLj0eKFW3BQZE8"
         )
      ]
```

**Comment by giedriusStan** [comment]
Then everything appears to be normal. I'm guessing it is an issue with argos on your shell version. I never tested it on 3.28.4 so it's possible that this issue will be fixed in your next upgrade

**Comment by nickjcoco** [comment]
Cool. I can handle that. Thanks for taking the time to help. It does work without issue on my laptop running Ubuntu 19.04 and I believe Gnome Shell 3.32.2 (I just loaded it on their last night). So you’re probably on the nose there. Appreciate it!
